#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-pdfbox-graphics2d
Version  : graphics2d.0.12
Release  : 1
URL      : https://github.com/rototor/pdfbox-graphics2d/archive/graphics2d-0.12.tar.gz
Source0  : https://github.com/rototor/pdfbox-graphics2d/archive/graphics2d-0.12.tar.gz
Source1  : https://repo.gradle.org/gradle/libs-releases/de/rototor/pdfbox/graphics2d/0.12/graphics2d-0.12.jar
Source2  : https://repo.gradle.org/gradle/libs-releases/de/rototor/pdfbox/graphics2d/0.12/graphics2d-0.12.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-pdfbox-graphics2d-data = %{version}-%{release}
Requires: mvn-pdfbox-graphics2d-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
# pdfbox-graphics2d
Graphics2D Bridge for Apache PDFBox
## Intro
Using this library you can use any Graphics2D API based SVG / graph / chart library
to embed those graphics as vector drawing in a PDF.

%package data
Summary: data components for the mvn-pdfbox-graphics2d package.
Group: Data

%description data
data components for the mvn-pdfbox-graphics2d package.


%package license
Summary: license components for the mvn-pdfbox-graphics2d package.
Group: Default

%description license
license components for the mvn-pdfbox-graphics2d package.


%prep
%setup -q -n pdfbox-graphics2d-graphics2d-0.12

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-pdfbox-graphics2d
cp LICENSE-2.0.txt %{buildroot}/usr/share/package-licenses/mvn-pdfbox-graphics2d/LICENSE-2.0.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/de/rototor/pdfbox/graphics2d/0.12
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/de/rototor/pdfbox/graphics2d/0.12/graphics2d-0.12.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/de/rototor/pdfbox/graphics2d/0.12
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/de/rototor/pdfbox/graphics2d/0.12/graphics2d-0.12.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/de/rototor/pdfbox/graphics2d/0.12/graphics2d-0.12.jar
/usr/share/java/.m2/repository/de/rototor/pdfbox/graphics2d/0.12/graphics2d-0.12.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-pdfbox-graphics2d/LICENSE-2.0.txt
